apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "movie-chart.fullname" . }}
  labels:
    {{- include "movie-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "movie-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "movie-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: movie-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          {{- with .Values.extraEnv }}
          env:
            {{- range $key, $val := . }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "movie-chart.fullname" . }}-config
            - secretRef:
                name: {{ include "movie-chart.fullname" . }}-secret
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
