{{- if .Values.mongo.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "movie-chart.mongoName" . }}
  labels:
    {{- include "movie-chart.labels" . | nindent 4 }}
    component: mongo
spec:
  serviceName: {{ include "movie-chart.mongoName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "movie-chart.selectorLabels" . | nindent 6 }}
      component: mongo
  template:
    metadata:
      labels:
        {{- include "movie-chart.selectorLabels" . | nindent 8 }}
        component: mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mongo.storage }}
{{- end }}
