apiVersion: v2
name: movie-chart
description: Movie API Helm chart
type: application
version: 0.2.0
appVersion: "1.1"

dependencies:
  - name: mongodb
    version: "15.6.26"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
